name: Create and Validate Atlas Playbook

on:
  push:
    paths:
      - "src/**"
      - "**/*.yaml"
      - "**/*.yml"

jobs:
  build:
    runs-on: windows-latest
    
    env:
      # Store the password in an environment variable for better security and readability
      APBX_PASSWORD: malte 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Build CAB
        run: |
          Write-Output "Building package..."
          .\start-build.ps1 -Thumbprint $thumbprint

          Write-Output "Copying package to AtlasModules..."
          Get-ChildItem -File -Recurse -Filter *.cab | ForEach-Object {
            Copy-Item -Path $_.FullName -Destination $packagePath -Force
          }

          Write-Output "Cleaning up..."
          .\clean.ps1
        working-directory: ..

      - name: Create playbook
        id: create-pb
        if: ${{ !startsWith(github.ref, 'refs/heads/na-') }}
        run: |
          $pbName = "Atlas Playbook $($env:GITHUB_SHA.Substring(0,8))"
          echo "Making a password protected ($env:APBX_PASSWORD) ZIP of playbook files: $pbName"
          & ..\dependencies\local-build.ps1 -ReplaceOldPlaybook -AddLiveLog -Removals Verification, WinverRequirement -FileName $pbName -Password $env:APBX_PASSWORD
          echo "Moving $pbName.apbx to release-zip folder..."
          Move-Item "$pbName.apbx" "../release-zip"
        working-directory: src/playbook

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ steps.create-pb.outcome != 'skipped' }}
        with:
          name: Atlas Playbook
          path: release-zip/*
          if-no-files-found: error
